"""Update documents and add missing tables

Revision ID: 46fab2e8830a
Revises: ad7832acf68c
Create Date: 2026-04-13 10:47:46.358002

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '46fab2e8830a'
down_revision: Union[str, Sequence[str], None] = 'ad7832acf68c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_sessions_id'), 'chat_sessions', ['id'], unique=False)
    
    # Check if team_data exists before dropping to avoid errors
    # op.drop_table('team_data')

    with op.batch_alter_table('document_chunk_metadata', schema=None) as batch_op:
        batch_op.add_column(sa.Column('content_type', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('image_index', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('ocr_confidence', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('ocr_engine', sa.String(), nullable=True))

    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_path', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('file_size', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('file_type', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('file_hash', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('chunk_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('error_message', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_documents_file_hash'), ['file_hash'], unique=False)
        batch_op.drop_index('ix_documents_filename')
        batch_op.drop_column('upload_time')
    
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('upload_time', sa.DATETIME(), nullable=True))
        batch_op.drop_index(batch_op.f('ix_documents_file_hash'))
        batch_op.create_index('ix_documents_filename', ['filename'], unique=False)
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')
        batch_op.drop_column('error_message')
        batch_op.drop_column('chunk_count')
        batch_op.drop_column('file_hash')
        batch_op.drop_column('file_type')
        batch_op.drop_column('file_size')
        batch_op.drop_column('file_path')

    with op.batch_alter_table('document_chunk_metadata', schema=None) as batch_op:
        batch_op.drop_column('ocr_engine')
        batch_op.drop_column('ocr_confidence')
        batch_op.drop_column('image_index')
        batch_op.drop_column('content_type')

    op.create_table('team_data',
    sa.Column('team', sa.TEXT(), nullable=True),
    sa.Column('country', sa.TEXT(), nullable=True),
    sa.Column('season', sa.INTEGER(), nullable=True),
    sa.Column('total_goals', sa.INTEGER(), nullable=True)
    )
    op.drop_index(op.f('ix_chat_sessions_id'), table_name='chat_sessions')
    op.drop_table('chat_sessions')
    # ### end Alembic commands ###
