"""thêm trường is_active cho user

Revision ID: 572a85b65787
Revises: 46fab2e8830a
Create Date: 2026-04-14 12:51:50.518243

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '572a85b65787'
down_revision: Union[str, Sequence[str], None] = '46fab2e8830a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('team_data') # Table may not exist in current DB, skipping
    op.add_column('chats', sa.Column('session_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'chats', 'chat_sessions', ['session_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'chats', type_='foreignkey')
    op.drop_column('chats', 'session_id')
    op.create_table('team_data',
    sa.Column('team', sa.TEXT(), nullable=True),
    sa.Column('country', sa.TEXT(), nullable=True),
    sa.Column('season', sa.INTEGER(), nullable=True),
    sa.Column('total_goals', sa.INTEGER(), nullable=True)
    )
    # ### end Alembic commands ###
