"""Sync database with latest document CRUD changes

Revision ID: 8861fa99fa9d
Revises: 572a85b65787
Create Date: 2026-04-21 11:59:04.210312

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8861fa99fa9d'
down_revision: Union[str, Sequence[str], None] = '572a85b65787'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chats') as batch_op:
        batch_op.create_foreign_key('fk_chats_sessions', 'chat_sessions', ['session_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'chats', type_='foreignkey')
    # ### end Alembic commands ###
