"""enterprise_features

Revision ID: bae6804b549d
Revises: 8861fa99fa9d
Create Date: 2026-04-24 15:16:30.011423

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bae6804b549d'
down_revision: Union[str, Sequence[str], None] = '8861fa99fa9d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('chat_sessions', sa.Column('summary', sa.Text(), nullable=True))
    # op.add_column('chat_sessions', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # op.add_column('documents', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    # op.add_column('documents', sa.Column('visibility', sa.String(), nullable=True))
    # op.add_column('documents', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    # op.add_column('users', sa.Column('department', sa.String(length=100), nullable=True))
    # op.add_column('users', sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False))
    with op.batch_alter_table('users') as batch_op:
        batch_op.alter_column('role',
                   existing_type=sa.VARCHAR(length=5),
                   type_=sa.Enum('USER', 'MANAGER', 'ADMIN', name='roleenum'),
                   existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
               existing_type=sa.Enum('USER', 'MANAGER', 'ADMIN', name='roleenum'),
               type_=sa.VARCHAR(length=5),
               existing_nullable=False)
    op.drop_column('users', 'is_active')
    op.drop_column('users', 'department')
    op.drop_column('documents', 'deleted_at')
    op.drop_column('documents', 'visibility')
    op.drop_column('documents', 'is_deleted')
    op.drop_column('chat_sessions', 'updated_at')
    op.drop_column('chat_sessions', 'summary')
    # ### end Alembic commands ###
